name: Build and Publish Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:  doubleu/processing-plan-service:latest
          cache-from: type=registry,ref= doubleu/processing-plan-service:latest
          cache-to: type=inline

      # - 
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image
      #   with:
      #     image: doubleu/processing-plan-service
      #     registry: docker.io
      #     tags: v1, latest
      #     dockerfile: Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #   env:
      #     REDIS: ${{ secrets.REDIS }}
      #     AMQP: ${{ secrets.AMQP }}